### ISSUE TITLE
Encoding change

### ISSUE THREAD

**Issue by goncalo-pereira** [jjmrocha/jsondoc#5]
I would like to propose that the encoding of the values between -0.0000000001 and 0.0000000001 also uses the compact format.

Today:
erl> jsondoc:encode([{value, 0.0}]).
<<"{\"value\":0.00000000000000000000e+00}">>
erl> jsondoc:encode([{value, 0.1}]).
<<"{\"value\":0.1}">>

My proposal:
erl> jsondoc:encode([{value, 0.0}]).
<<"{\"value\":0.0}">>
erl> jsondoc:encode([{value, 0.1}]).
<<"{\"value\":0.1}">>

Thank you.

Best regards,
Gonçalo Pereira

**Comment by jjmrocha** [comment]
Please fill free to submit a pull request

**Comment by goncalo-pereira** [comment]
Submited the pull request

**Comment by jjmrocha** [comment]
We can add a special case for 0.0

**Comment by goncalo-pereira** [comment]
Thank you.
